### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by warci** [minhng92/odoo-17-docker-compose#1]
Hi,
I'm running on OSX Sonoma. When trying to initialize the database I receive:
`Database creation error: Access Denied`

I have performed the permission modifications as mentioned in the readme.
The docker logs don't seem to mention anything relevant.

Thanks for providing this awesome docker-compose setup!

[odoo_docker.log](https://github.com/minhng92/odoo-17-docker-compose/files/13463341/odoo_docker.log)

**Comment by minhng92** [comment]
Hi @warci ,

In your odoo_docker.log I can see that your database has started successfully. The issue may be incorrect "Master password".
The password to create new database on Odoo form is ["admin_passwd" in odoo.conf](https://github.com/minhng92/odoo-17-docker-compose/blob/9ab0a213c1393f3789ac5a0aa14171f5ba681530/etc/odoo.conf#L60).

Please try again with the following step:
1. Change **admin_passwd** in etc/odoo.conf to XXX (your favorite one)
2. Restart Odoo container `docker-compose restart`
3. Initialize the database again with the password XXX you have set.

Hope that it helps.

**Comment by warci** [comment]
Can't believe I missed this. Thank you so much and my apologies for asking dumb questions :)
