### ISSUE TITLE
Develop Mode

### ISSUE THREAD

**Issue by mmdanny89** [minhng92/odoo-17-docker-compose#15]
Its possible run this instance for debug and develop mode?

**Comment by minhng92** [comment]
Yes, it is @mmdanny89 . This instance support developer mode.

To activate debug/developer mode, please follow official docs: https://www.odoo.com/documentation/17.0/applications/general/developer_mode.html

**Comment by mmdanny89** [comment]
thank you @minhng92 i will make tests.

**Comment by mmdanny89** [comment]
i want to debug code with vscode
