### ISSUE TITLE
where to find odoo-bin?

### ISSUE THREAD

**Issue by muramez** [minhng92/odoo-17-docker-compose#17]
hi, could you tell me, wehre i can find odoo-bin inside the docker environment? thanks a lot

**Comment by muramez** [comment]
Yes, thanks. Am 31.12.2024 um 10:09 schrieb David Richrdson ***@***.***>:﻿
@muramez did you find it?

**Comment by minhng92** [comment]
Hi @flowersofpepper ,

The odoo-bin file inside the Docker container is located at `/usr/bin/odoo`.

The steps to locate it are as follows:

```bash
$ docker exec -it <container name> bash
$ which odoo
/usr/bin/odoo
```
