### ISSUE TITLE
How to upgrade from version 16 to 17

### ISSUE THREAD

**Issue by liamvn** [minhng92/odoo-17-docker-compose#2]

**Comment by minhng92** [comment]
Hi @liamvn ,

With Odoo community version, you have to upgrade source code of the addons and migrate database yourself.
With Odoo enterprise version, we have the upgrade support tool @ [https://upgrade.odoo.com/](https://upgrade.odoo.com/)
Both versions require the (custom) addons which are compatible to Odoo version 17.

**Comment by liamvn** [comment]
Hi @minhng92
Thank you for answer. But, how can I migrate my database to a newer version, I can't find documentation for this.

**Comment by minhng92** [comment]
@liamvn 
There's no official documentation for community version from Odoo. So just do it "manually" by ourself.
Using export-import feature might help. Export data from old version and import to Odoo 17. If the data structure is not compatible, we'll manually process on the data.
