### ISSUE TITLE
Volume for filestore

### ISSUE THREAD

**Issue by euroblaze** [minhng92/odoo-17-docker-compose#4]
Hello @minhng92 

Have you thought about creating a separate volume for the filestore?

Thanks for your feedback!

**Comment by minhng92** [comment]
Hi @euroblaze ,

The current setup in the docker-compose.yml file stores the filestore in the ./etc directory on the host. The default configuration is intentionally kept simple and portable.

Feel free to customize it for your project as needed.

**Comment by euroblaze** [comment]
> The current setup in the docker-compose.yml file stores the filestore in the ./etc directory on the host. The default configuration is intentionally kept simple and portable.

Thank you, that's perfect!

Ps: really like your v17 Docker; so far the tests are going great!
