### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by euroblaze** [minhng92/odoo-17-docker-compose#6]
@minhng92 

I'm a bit of a beginner, and am really struggling to understand the relationship between docker-compose.yml file published here, and where the `docker-compose` command actually gets the Odoo sources from.

Where could I obtain the Dockerfile for v17 from?

Thank you in advance!

**Comment by minhng92** [comment]
Hello @euroblaze,

In the docker-compose file, we utilize the Docker image "odoo:17", which already contains the packaged Odoo sources.

For further details, you can refer to the Dockerfile available at this link: [Odoo Docker Hub](https://hub.docker.com/_/odoo).

Best regards,
Minh
